version: "3"

services:
  drugs-importer:
    build:
      context: ./Importer/
    container_name: drugs-importer
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
      - "./drug-importer.sh:/drug-importer.sh"

  api:
    build:
      context: ./API/
    container_name: api
    environment:
      API_PORT: 8080
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
