name: CI/Linter

  linter:
    name: Build & ESLint
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    defaults:
      run:
        working-directory: API

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        run: npm install

      - name: Compiling TypeScript
        run: npx tsc
      
      - name: Executing Linter
        run: npm test
