name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Building Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Building docker-compose
        run: docker-compose build

      - name: Running docker-compose
        run: docker-compose up -d

      - name: Show docker-compose containers
        run: docker ps

      - name: Closing docker-compose
        run: docker-compose down
