name: CI

on:
  push:
    branches: [ master, dev_API ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    name: Project Linter (ESLINT)
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    env:
      workDir: ./API/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        run: npm install
        working-directory: {{ env.workDir }}

      - name: Compiling TypeScript
        run: npx tsc
        working-directory: {{ env.workDir }}
      
      - name: Executing Linter
        run: npm test
        working-directory: {{ env.workDir }}

  build:
    name: Building Project
    runs-on: ubuntu-20.04

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: Drugs
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: Building docker-compose
        run: docker-compose build

      - name: Running docker-compose
        run: docker-compose up -d

      - name: Show docker-compose containers
        run: docker ps

      - name: Closing docker-compose
        run: docker-compose down
