name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Building Project
    runs-on: ubuntu-latest

    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: Drugs
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: Building docker-compose
        run: docker-compose build

      - name: Running docker-compose
        run: docker-compose up -d

      - name: Show docker-compose containers
        run: docker ps

      - name: Closing docker-compose
        run: docker-compose down
